# Generated by Django 3.0.8 on 2020-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('apellido', models.TextField(blank=True)),
                ('dni', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
