# Generated by Django 3.0.8 on 2020-08-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obras', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canale.ObrasSociales'),
        ),
    ]
