# Generated by Django 3.0.8 on 2020-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canale', '0002_auto_20200813_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
