# Generated by Django 3.0.8 on 2020-08-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canale', '0003_auto_20200813_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cuil',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=64)),
                ('estado', models.IntegerField(blank=True)),
                ('obra_social', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='canale.ObrasSociales')),
            ],
        ),
    ]
