# Generated by Django 3.0.8 on 2020-08-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canale', '0004_auto_20200814_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicas',
            name='estado',
            field=models.CharField(max_length=64),
        ),
    ]
